### ISSUE TITLE
Audio Bug

### ISSUE THREAD

**Issue by bleezy209** [acreloaded/acr#19]
I was in a middle of a match everything was working fine but I fired a few times and all the sound cut out until I join a different match. I tried going to settings and changed the volume up and down and messed with the other audio setting but it didn't do anything. Thx for all your help best gaming community.  :)

**Comment by rBok6** [comment]
Yeah I'm having the same issue. Please ACR needs a fix for this.

**Comment by theonlypwner** [comment]
Use `openal32_RemoveThisPartToUseOpenAL-Soft.dll` by renaming it to `openal32.dll`.
Don't use `oalinst.exe`, which I renamed to `oalinst_not_recommended.exe` in commit 827bed0627f0afb4e20f7a0b754c8dac9605cfca.
