### ISSUE TITLE
Bot instant die

### ISSUE THREAD

**Issue by OlivierLamiraux** [acreloaded/acr#199]
With a fresh install of Release 2.6.3 (2.7 beta 3) when I try a match with Bot, Bot is killed instantly. Something need to be done for play vs Bot ?

**Comment by theonlypwner** [comment]
If the bots respawn properly, then it's just an issue when they spawn at the beginning of a match.

In that case, it would be a minor bug.

**Comment by theonlypwner** [comment]
This is closed because d7f077bd446cd5003c664c68e3f080a702c2ec0d should fix random bot suicides because bots thinks they're stuck with they aren't.
