### ISSUE TITLE
error: couldn't load texture packages/misc/notexture.jpg

### ISSUE THREAD

**Issue by WPFilmmaker** [acreloaded/acr#209]
```
stuff@stuff-VirtualBox:~/Desktop$ cd /home/stuff/Downloads/ac/bin_unix
stuff@stuff-VirtualBox:~/Downloads/ac/bin_unix$ chmod +x linux_64_client
stuff@stuff-VirtualBox:~/Downloads/ac/bin_unix$ ./linux_64_client
init: sdl
init: net
init: world
init: video: sdl
init: video: mode
init: video: misc
init: gl
Renderer: llvmpipe (LLVM 5.0, 256 bits) (VMware, Inc.)
Driver: 3.0 Mesa 17.2.8
couldn't load texture packages/misc/notexture.jpg
could not find core textures (hint: run ACR from the parent of the bin directory) (Couldn't open packages/misc/notexture.jpg)
stuff@stuff-VirtualBox:~/Downloads/ac/bin_unix$
```

I am using the latest AC version on Lubuntu 16.04.3

**Comment by Noah11012** [comment]
![notexture](https://user-images.githubusercontent.com/26338478/38838565-ad37d75a-41a4-11e8-8911-3435f941351a.jpg)

Download the image and place it in your /home/stuff/Downloads/ac/packages/misc directory.

**Comment by Noah11012** [comment]
Also, now that I looked at the commands you ran, you need to run the script file client.sh in the root directory of AssaultCube Reloaded instead of just running the binary file in bin_unix. That could be a reason why you're having an issue.
