### ISSUE TITLE
Silent crashes 

### ISSUE THREAD

**Issue by the1glorfindel** [acreloaded/acr#212]
The game has been silently crashing on me pretty much since I started playing it a while back.
I don't know the version for sure, but the file name is "acr_02_06_03-l.zip". Is there a suffix to show the version?
Basically I launch the game from cli, and it plays fine for however long, and then crashes. I've tried to find a specific triggering event but thus far no dice. I hope I have included enough info. 
The following is the terminal readout:

[terminal.log](https://github.com/acreloaded/acr/files/2431217/terminal.log)

**Comment by the1glorfindel** [comment]
Eh. is there a way to hide all the output in a spoiler of some sort? just so there isn't so much to scroll through each time... still mastering github

**Comment by theonlypwner** [comment]
Your log has been placed into an attachment. Unfortunately, the log doesn't provide enough information to identify the problem.

I recommend trying a newer version, ACR 2.7.
