### ISSUE TITLE
Is ACR fully Free Software?

### ISSUE THREAD

**Issue by asddsaz** [acreloaded/acr#217]
**Question** Is ACR 100% [free software](https://www.wikipedia.org/wiki/Free_software)?
I remember Assault Cube being Contrib, did ACR fix this?
Source: https://packages.debian.org/stretch/assaultcube

**Comment by theonlypwner** [comment]
The source code is under the Cube License (similar to zlib License).

Media files are copyrighted, but the "entire unmodified package(s)" may be redistributed.
