### ISSUE TITLE
AC Server Compatibility

### ISSUE THREAD

**Issue by notanewbie** [acreloaded/acr#222]
How come the AC servers aren't compatible with AssaultCube Reloaded?

**Comment by theonlypwner** [comment]
[We previously voted against it](http://forum.acr.victorz.ca/thread-1256.html).

**Comment by theonlypwner** [comment]
Duplicate of #59.

**Comment by theonlypwner** [comment]
[We previously voted against it](http://forum.acr.victorz.ca/thread-1256.html).

Duplicate of #59.

**Comment by theonlypwner** [comment]
Duplicate of #59
