### ISSUE TITLE
OpenAL Error (A003): invalid value, line 156

### ISSUE THREAD

**Issue by Mte90** [acreloaded/acr#250]
I am getting this error inside the game and in the console on linux: `OpenAL Error (A003): invalid value, line 156`

**Comment by Mte90** [comment]
Seems that compiling the game fixed the problem maybe since the release there was some changes with the various dependencies

**Comment by theonlypwner** [comment]
This seems to be similar to #215.

**Comment by theonlypwner** [comment]
I'm closing this as a duplicate.

If you can reproduce the issue, please try to get a stacktrace with line numbers (https://github.com/acreloaded/acr/issues/215#issuecomment-759891092) and post it there.

**Comment by theonlypwner** [comment]
Duplicate of #215
