### ISSUE TITLE
Numbers floating without reasons

### ISSUE THREAD

**Issue by Mte90** [acreloaded/acr#251]
![20200315_13 51 08_ac_terros_deathmatch](https://user-images.githubusercontent.com/403283/76702751-ab359b00-66cc-11ea-8c87-1c7c79c8ff19.jpg)
![20200315_13 49 19_ac_venison_deathmatch](https://user-images.githubusercontent.com/403283/76702759-b12b7c00-66cc-11ea-97f5-1e0a8f9dafa0.jpg)
As you can see from the screen there are this numbers floating withot no reasons.

**Comment by theonlypwner** [comment]
These are damage indicator number particles, which are currently still in development.

They will be cleaned up (numbers will be merged if they occur near the same time). Also, there will be an option to configure the time they appear (0 to disable).

**Comment by Mte90** [comment]
It is possible to disable them? they are kind of confusing during the game.

**Comment by theonlypwner** [comment]
I already mentioned they will be configurable when the next version is released.

Remember, the `master` branch is the latest *development* version, not the latest *released* version.

**Comment by Mte90** [comment]
Ok I was asking because this project is without a readme so is difficult to find resources to understand what is the status. I luckily found with google the wiki that is not mentioned there.
