### ISSUE TITLE
Assaultcube crash

### ISSUE THREAD

**Issue by ghost** [acreloaded/acr#252]
ACR error (11) (Couldn't open packages/maps/official/preview/acr_recreation.jpg)
OpenAL Error (A004): invalid operation, line 367

OS: Arch Linux x86_64
Kernel: 5.7.5-arch1-1

**Comment by theonlypwner** [comment]
duplicate of #215?

**Comment by Pauloo27** [comment]
I got the same error. I'm no Arch as well.

I tried to clone the repo and compile it myself, the error persist.

**Comment by theonlypwner** [comment]
I'm closing this as a duplicate.

If you can reproduce the issue, please try to get a stacktrace with line numbers (https://github.com/acreloaded/acr/issues/215#issuecomment-759891092) and post it there.

**Comment by theonlypwner** [comment]
duplicate of #215

**Comment by theonlypwner** [comment]
Duplicate of #215
