### ISSUE TITLE
Multiple Crosshair ?

### ISSUE THREAD

**Issue by inukaze** [acreloaded/acr#258]
Hi there i just want to know how i can fix this : 
[![20211220-05-23-48-ac-arabian-t-deathmatch.jpg](https://i.postimg.cc/SxSfz9QS/20211220-05-23-48-ac-arabian-t-deathmatch.jpg)](https://postimg.cc/qzF3PzCS)

i just want one central crosshair, the anothers 4 around the central i don't want it

**Comment by theonlypwner** [comment]
Take a look at the `/crosshairmode` command.
